In [ ]:
import kaolin
import torch
import os
import numpy as np
import matplotlib.pyplot as plt
import polyscope as ps

# import diffvoronoi
import pygdel3d
import sdfpred_utils.sdfpred_utils as su
import sdfpred_utils.loss_functions as lf
from pytorch3d.loss import chamfer_distance
from pytorch3d.ops import knn_points, knn_gather
import torch
from torch import nn

# cuda devices
device = torch.device("cuda:0")
print("Using device: ", torch.cuda.get_device_name(device))

# Improve reproducibility
torch.manual_seed(69)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(69)

input_dims = 3
lr_sites = 0.005
# lr_model = 0.00001
destination = "./images/autograd/End2End_DCCVT_interpolSDF/"
model_trained_it = ""
ROOT_DIR = "/home/wylliam/dev/Kyushu_experiments"

# mesh = ["sphere"]

# mesh = ["hole_gargoyle", "/home/wylliam/dev/Kyushu_experiments/data/gargoyle"]
# trained_model_path = f"/home/wylliam/dev/HotSpot/log/3D/pc/HotSpot-all-2025-04-24-18-16-03/gargoyle/gargoyle/trained_models/model{model_trained_it}.pth"

# mesh = [
#     "gargoyle",
#     f"{ROOT_DIR}/mesh/thingi32/64764",
# ]
# trained_model_path = f"{ROOT_DIR}/hotspots_model/thingi32/64764.pth"


# mesh = ["zombie", f"{ROOT_DIR}/mesh/thingi32/398259"]
# trained_model_path = f"{ROOT_DIR}/hotspots_model/thingi32/398259.pth"

mesh = ["gargoyle_unconverged", "/home/wylliam/dev/Kyushu_experiments/mesh/gargoyle_unconverged"]
trained_model_path = f"/home/wylliam/dev/HotSpot/log/3D/pc/HotSpot-all-2025-04-24-18-16-03/gargoyle/gargoyle/trained_models/model_500.pth"


# mesh = ["chair", "/home/wylliam/dev/Kyushu_experiments/data/chair"]
# trained_model_path = f"/home/wylliam/dev/HotSpot/log/3D/pc/HotSpot-all-2025-05-02-17-56-25/chair/chair/trained_models/model{model_trained_it}.pth"

# mesh = ["bunny", "/home/wylliam/dev/Kyushu_experiments/data/bunny"]
# trained_model_path = f"/home/wylliam/dev/HotSpot/log/3D/pc/HotSpot-all-2025-04-25-17-32-49/bunny/bunny/trained_models/model{model_trained_it}.pth"


Using device:  NVIDIA GeForce RTX 3090


In [2]:
num_centroids = 16**3
grid = 32  # 128
print("Creating new sites")
noise_scale = 0.005
domain_limit = 1
x = torch.linspace(-domain_limit, domain_limit, int(round(num_centroids ** (1 / 3))))
y = torch.linspace(-domain_limit, domain_limit, int(round(num_centroids ** (1 / 3))))
z = torch.linspace(-domain_limit, domain_limit, int(round(num_centroids ** (1 / 3))))
meshgrid = torch.meshgrid(x, y, z)
meshgrid = torch.stack(meshgrid, dim=3).view(-1, 3)

# add noise to meshgrid
meshgrid += torch.randn_like(meshgrid) * noise_scale


sites = meshgrid.to(device, dtype=torch.float32).requires_grad_(True)

print("Sites shape: ", sites.shape)
print("Sites: ", sites[0])
ps.init()


Creating new sites
Sites shape:  torch.Size([4096, 3])
Sites:  tensor([-1.0027, -1.0065, -0.9978], device='cuda:0', grad_fn=<SelectBackward0>)
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 3.3.0 NVIDIA 575.64.03


/home/wylliam/dev/Kyushu_experiments-1/venv/lib/python3.12/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4314.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [ ]:
# import torch


# def z_axis_weights(points, mode="exp", strength=3.0, percentile_clip=(0.02, 0.98), eps=1e-12):
#     """
#     points: (N,3) or (1,N,3)
#     """
#     # --- normalize shape ---
#     if points.dim() == 3 and points.shape[0] == 1:
#         points = points.squeeze(0)
#     if not (points.dim() == 2 and points.shape[1] == 3):
#         raise ValueError(f"points must be (N,3) or (1,N,3); got {tuple(points.shape)}")

#     z = points[:, 2]

#     # Robust min-max -> z_norm in [0,1]
#     if percentile_clip is not None:
#         lo, hi = percentile_clip
#         z_lo = torch.quantile(z, lo)
#         z_hi = torch.quantile(z, hi)
#     else:
#         z_lo, z_hi = z.min(), z.max()

#     denom = (z_hi - z_lo).abs()
#     if denom < 1e-12:
#         # all z ~ equal -> uniform weights
#         return torch.ones_like(z)

#     z_norm = ((z - z_lo) / (denom + eps)).clamp(0.0, 1.0)

#     if mode == "linear":
#         w = 1.0 - z_norm
#     elif mode == "poly":
#         p = float(strength)
#         w = (1.0 - z_norm).pow(p)
#     elif mode == "exp":
#         lam = float(strength)
#         w = torch.exp(-lam * z_norm)
#     elif mode == "sigmoid":
#         k = float(strength)
#         w = torch.sigmoid(-k * (z_norm - 0.5))
#     else:
#         raise ValueError("mode must be one of: linear | poly | exp | sigmoid")

#     return (w - w.min()).clamp_min(0) + eps


# def weighted_subsample(points, M, weights, *, allow_replacement=None):
#     """
#     points:   (N,3) or (1,N,3)
#     weights:  (N,) or (1,N)
#     If allow_replacement is None: auto True when M>N, else False.
#     """
#     # --- normalize shapes ---
#     if points.dim() == 3 and points.shape[0] == 1:
#         points = points.squeeze(0)
#     if not (points.dim() == 2 and points.shape[1] == 3):
#         raise ValueError(f"points must be (N,3) or (1,N,3); got {tuple(points.shape)}")

#     if weights.dim() == 2 and weights.shape[0] == 1:
#         weights = weights.squeeze(0)
#     if weights.dim() != 1 or weights.shape[0] != points.shape[0]:
#         raise ValueError(f"weights must be (N,) matching points; got {tuple(weights.shape)} vs N={points.shape[0]}")

#     N = points.shape[0]
#     if allow_replacement is None:
#         allow_replacement = M > N

#     w = (weights.float() - weights.min()).clamp_min(0) + 1e-12
#     M_eff = min(M, N) if not allow_replacement else M

#     idx = torch.multinomial(w, M_eff, replacement=allow_replacement)
#     return points[idx], idx


In [ ]:
# LOAD MODEL WITH HOTSPOT

import sys

if mesh[0] != "sphere":
    sys.path.append("3rdparty/HotSpot")
    from dataset import shape_3d
    import models.Net as Net

    loss_type = "igr_w_heat"
    loss_weights = [350, 0, 0, 1, 0, 0, 20]

    train_set = shape_3d.ReconDataset(
        file_path=mesh[1] + ".ply",
        n_points=grid * grid * 150,  # 15000, #args.n_points,
        n_samples=10001,  # args.n_iterations,
        grid_res=256,  # args.grid_res,
        grid_range=1.1,  # args.grid_range,
        sample_type="uniform_central_gaussian",  # args.nonmnfld_sample_type,
        sampling_std=0.5,  # args.nonmnfld_sample_std,
        n_random_samples=7500,  # args.n_random_samples,
        resample=True,
        compute_sal_dist_gt=(True if "sal" in loss_type and loss_weights[5] > 0 else False),
        scale_method="mean",  # "mean" #args.pcd_scale_method,
    )

    model = Net.Network(
        latent_size=0,  # args.latent_size,
        in_dim=3,
        decoder_hidden_dim=128,  # args.decoder_hidden_dim,
        nl="sine",  # args.nl,
        encoder_type="none",  # args.encoder_type,
        decoder_n_hidden_layers=5,  # args.decoder_n_hidden_layers,
        neuron_type="quadratic",  # args.neuron_type,
        init_type="mfgi",  # args.init_type,
        sphere_init_params=[1.6, 0.1],  # args.sphere_init_params,
        n_repeat_period=30,  # args.n_repeat_period,
    )
    model.to(device)

    ######
    test_dataloader = torch.utils.data.DataLoader(
        train_set, batch_size=1, shuffle=False, num_workers=0, pin_memory=False
    )
    test_data = next(iter(test_dataloader))
    mnfld_points = test_data["mnfld_points"].to(device)

    # add noise to mnfld_points
    # mnfld_points += torch.randn_like(mnfld_points) * (2 / 32) * (32 / 100)

    mnfld_points.requires_grad_()
    print("mnfld_points shape: ", mnfld_points.shape)
    if torch.cuda.is_available():
        map_location = torch.device("cuda")
    else:
        map_location = torch.device("cpu")
    model.load_state_dict(torch.load(trained_model_path, weights_only=True, map_location=map_location))
    sdf0 = model(sites)

else:

    def sphere_sdf(points: torch.Tensor, center: torch.Tensor, radius: float) -> torch.Tensor:
        """
        Compute the SDF of a sphere at given 3D points.

        Args:
            points: (N, 3) tensor of 3D query points
            center: (3,) tensor specifying the center of the sphere
            radius: float, radius of the sphere

        Returns:
            sdf: (N,) tensor of signed distances
        """
        return torch.norm(points - center, dim=-1) - radius

    def sphere_sdf_with_noise(
        points: torch.Tensor, center: torch.Tensor, radius: float, noise_amplitude=0.05
    ) -> torch.Tensor:
        """
        Sphere SDF with smooth directional noise added near the surface.

        Args:
            points: (N, 3)
            center: (3,)
            radius: float
            noise_amplitude: float

        Returns:
            sdf: (N,)
        """
        rel = points - center
        norm = torch.norm(rel, dim=-1)  # (N,)
        base_sdf = norm - radius  # (N,)

        # Smooth periodic noise based on direction
        unit_dir = rel / (norm.unsqueeze(-1) + 1e-9)  # (N,3)
        noise = torch.sin(10 * unit_dir[:, 0]) * torch.sin(10 * unit_dir[:, 1]) * torch.sin(10 * unit_dir[:, 2])

        # Weight noise so it mostly affects surface area
        falloff = torch.exp(-20 * (base_sdf**2))  # (N,) ~1 near surface, ~0 far
        sdf = base_sdf + noise_amplitude * noise * falloff

        return sdf

    # generate points on the sphere
    mnfld_points = torch.randn(grid * grid * 150, 3, device=device)
    mnfld_points = mnfld_points / torch.norm(mnfld_points, dim=-1, keepdim=True) * 0.5
    mnfld_points = mnfld_points.unsqueeze(0).requires_grad_()
    sdf0 = sphere_sdf(sites, torch.zeros(3).to(device), 0.50)
    # sdf0 = sphere_sdf_with_noise(sites, torch.zeros(3).to(device), 0.50, noise_amplitude=0.1)


# add mnfld points with random noise to sites
N = mnfld_points.squeeze(0).shape[0]
num_samples = 18**3 - (num_centroids)
num_samples = 16**3
idx = torch.randint(0, N, (num_samples,))
sampled = mnfld_points.squeeze(0)[idx]
perturbed = sampled + (torch.rand_like(sampled) - 0.5) * noise_scale * 10


# M = 16**3  # 4096
# w = z_axis_weights(mnfld_points, mode="exp", strength=4.0)

# print("N =", mnfld_points.squeeze(0).shape[0], "M =", M)  # sanity check

# # Option A: keep unique samples only (if N<M, you’ll just get N)
# nonuni_pts, idx = weighted_subsample(mnfld_points, M, w, allow_replacement=False)

# # (optional) add your jitter
# perturbed = nonuni_pts + (torch.rand_like(nonuni_pts) - 0.5) * noise_scale


sites = torch.cat((sites, perturbed), dim=0)
sdf0 = model(sites)


# START FROM SPHERE EXPERIMENTS
# sdf0 = torch.norm(sites - torch.zeros(3).to(device), dim=-1) - 0.50

# make sites a leaf tensor
sites = sites.detach().requires_grad_()
print(sites.dtype)
print(sites.shape)
print(f"Allocated: {torch.cuda.memory_allocated() / 1e6} MB, Reserved: {torch.cuda.memory_reserved() / 1e6} MB")


sdf0 = sdf0.detach().squeeze(-1).requires_grad_()
print(sdf0.shape)
print(sdf0.is_leaf)


mnfld_points shape:  torch.Size([1, 153600, 3])
torch.float32
torch.Size([4096, 3])
Allocated: 63.913472 MB, Reserved: 65.011712 MB
torch.Size([4096])
True


In [5]:
sites_np = sites.detach().cpu().numpy()
d3dsimplices, _ = pygdel3d.triangulate(sites_np)
d3dsimplices = np.array(d3dsimplices)
# print("Delaunay simplices shape: ", d3dsimplices.shape)

# print("sites shape: ", sites.shape)


In [6]:
p, faces = su.cvt_extraction(sites, sdf0, d3dsimplices, True)
ps.register_point_cloud("cvt extraction", p.detach().cpu().numpy(), enabled=False)
ps.register_surface_mesh("cvt extraction", p.detach().cpu().numpy(), faces, back_face_policy="identical", enabled=True)

ps_cloud = ps.register_point_cloud("initial_cvt_grid+pc_gt", sites.detach().cpu().numpy(), enabled=False)
ps_cloud.add_scalar_quantity(
    "vis_grid_pred",
    sdf0.detach().cpu().numpy(),
    enabled=True,
    cmap="coolwarm",
    vminmax=(-0.00005, 0.00005),
)
mnf_cloud = ps.register_point_cloud("mnfld_points_pred", mnfld_points.squeeze(0).detach().cpu().numpy(), enabled=False)

v_vect, f_vect, sdf_verts, sdf_verts_grads, _ = su.get_clipped_mesh_numba(sites, None, d3dsimplices, False, sdf0, True)
ps_mesh = ps.register_surface_mesh(
    "sdf unclipped initial mesh",
    v_vect.detach().cpu().numpy(),
    f_vect,
    back_face_policy="identical",
    enabled=False,
)
# ps_vert = ps.register_point_cloud("sdf unclipped initial verts", v_vect.detach().cpu().numpy(), enabled=False)

v_vect, f_vect, _, _, _ = su.get_clipped_mesh_numba(sites, None, d3dsimplices, True, sdf0, True)
ps_mesh = ps.register_surface_mesh(
    "sdf clipped initial mesh",
    v_vect.detach().cpu().numpy(),
    f_vect,
    back_face_policy="identical",
    enabled=False,
)

d3dsimplices, _ = pygdel3d.triangulate(sites_np)
d3dsimplices = torch.tensor(d3dsimplices, device=device)
marching_tetrehedra_mesh = kaolin.ops.conversions.marching_tetrahedra(
    sites.unsqueeze(0), d3dsimplices, sdf0.unsqueeze(0), return_tet_idx=False
)
vertices_list, faces_list = marching_tetrehedra_mesh
v_vect = vertices_list[0]
faces = faces_list[0]

ps.register_surface_mesh(
    "init MTET",
    v_vect.detach().cpu().numpy(),
    faces.detach().cpu().numpy(),
    back_face_policy="identical",
    enabled=False,
)


# ps_cloud = ps.register_point_cloud("active sites", tet_probs[2].reshape(-1, 3).detach().cpu().numpy(), enabled=False)
# ps_cloud.add_vector_quantity("site step dir", tet_probs[0].reshape(-1, 3).detach().cpu().numpy())
# ps_vert.add_vector_quantity("verts step dir", tet_probs[1].detach().cpu().numpy())


ps.show()

In [ ]:
# SITES OPTIMISATION LOOP


cvt_loss_values = []
min_distance_loss_values = []
chamfer_distance_loss_values = []
eikonal_loss_values = []
domain_restriction_loss_values = []
sdf_loss_values = []
div_loss_values = []
loss_values = []

voroloss = lf.Voroloss_opt().to(device)


def train_DCCVT(
    sites,
    sites_sdf,
    max_iter=100,
    stop_train_threshold=1e-6,
    upsampling=0,
    lambda_weights=[0.1, 1.0, 0.1, 0.1, 1.0, 1.0, 0.1],
    voroloss_optim=False,
    Hotspot_model=None,
):
    if not voroloss_optim:
        optimizer = torch.optim.Adam(
            [
                {"params": [sites], "lr": lr_sites * 0.1},
                {"params": [sites_sdf], "lr": lr_sites * 0.1},
            ],
            betas=(0.8, 0.95),
        )
    else:
        optimizer = torch.optim.Adam([{"params": [sites], "lr": lr_sites * 0.1}])

    # scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.95)
    # scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.999)

    # optimizer_sites = torch.optim.Adam([{'params': [sites], 'lr': lr_sites}])
    # optimizer_sdf = torch.optim.SGD([{'params': [sites_sdf], 'lr': lr_sites}])
    # scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[80, 150, 200, 250], gamma=0.5)

    prev_loss = float("inf")
    best_loss = float("inf")
    upsampled = 0.0
    epoch = 0
    lambda_cvt = lambda_weights[0]
    lambda_chamfer = lambda_weights[4]
    lambda_shl = lambda_cvt / 10
    best_sites = sites.clone()
    best_sites.best_loss = best_loss
    sites_sdf_grads = None

    while epoch <= max_iter:
        # if epoch == 990:
        #     max_iter += 1000
        optimizer.zero_grad()
        # if mesh[0] == "sphere":
        #     # generate sphere sdf
        #     sites_sdf = sphere_sdf(sites, torch.zeros(3).to(device), 0.50)

        if not voroloss_optim:
            sites_np = sites.detach().cpu().numpy()
            # d3dsimplices = diffvoronoi.get_delaunay_simplices(sites_np.reshape(input_dims * sites_np.shape[0]))
            d3dsimplices, _ = pygdel3d.triangulate(sites_np)

            d3dsimplices = np.array(d3dsimplices)

            if epoch % 100 == 0 and epoch <= 500:
                eps_H = lf.estimate_eps_H(sites, d3dsimplices, multiplier=1.5 * 5).detach()
                print("Estimated eps_H: ", eps_H)
            elif epoch % 100 == 0 and epoch <= 800:
                eps_H = lf.estimate_eps_H(sites, d3dsimplices, multiplier=1.5 * 2).detach()
                print("Estimated eps_H: ", eps_H)

            build_mesh = False
            clip = True
            mtet = False
            sites_sdf_grads = None
            barycentric_weights = False
            ups_m = "tet_frame"
            no_mp = False

            if mtet:
                print("Using MTET")
                d3dsimplices = torch.tensor(d3dsimplices, device=device)
                marching_tetrehedra_mesh = kaolin.ops.conversions.marching_tetrahedra(
                    sites.unsqueeze(0), d3dsimplices, sites_sdf.unsqueeze(0), return_tet_idx=False
                )
                vertices_list, faces_list = marching_tetrehedra_mesh
                v_vect = vertices_list[0]
                faces = faces_list[0]
                print("v_vect shape: ", v_vect.shape)

            else:
                v_vect, faces_or_clippedvert, sites_sdf_grads, tets_sdf_grads, W = su.get_clipped_mesh_numba(
                    sites, None, d3dsimplices, clip, sites_sdf, build_mesh, False, barycentric_weights, no_mp
                )

                # _, bisectors_to_compute, _ = su.compute_zero_crossing_vertices_3d(
                #     sites, None, None, d3dsimplices, sites_sdf
                # )
                # bisectors = su.compute_all_bisectors_vectorized(sites, bisectors_to_compute)
                # bisectors_sdf = (sites_sdf[bisectors_to_compute[:, 0]] + sites_sdf[bisectors_to_compute[:, 1]]) / 2
                # bisectors_sdf_grad = (
                #     sites_sdf_grads[bisectors_to_compute[:, 0]] + sites_sdf_grads[bisectors_to_compute[:, 1]]
                # ) / 2
                # proj_bisectors = su.newton_step_clipping(bisectors_sdf_grad, bisectors_sdf, bisectors)  # (M,3)

            #  v_vect, faces_or_clippedvert = su.cvt_extraction(sites, sites_sdf, d3dsimplices, build_mesh)

            if build_mesh:
                triangle_faces = [[f[0], f[i], f[i + 1]] for f in faces_or_clippedvert for i in range(1, len(f) - 1)]
                triangle_faces = torch.tensor(triangle_faces, device=device)
                hs_p = su.sample_mesh_points_heitz(v_vect, triangle_faces, num_samples=mnfld_points.shape[0])
                chamfer_loss_mesh, _ = chamfer_distance(mnfld_points.detach(), hs_p.unsqueeze(0))
            else:
                chamfer_loss_mesh, _ = chamfer_distance(mnfld_points.detach(), v_vect.unsqueeze(0))
                # chamfer_loss_proj_bisect, _ = chamfer_distance(mnfld_points.detach(), proj_bisectors.unsqueeze(0))

                # chamfer_loss_mesh = 0.9 * chamfer_loss_mesh + 0.1 * chamfer_loss_proj_bisect

            if sites_sdf_grads is None:
                sites_sdf_grads, tets_sdf_grads, W = su.sdf_space_grad_pytorch_diego_sites_tets(
                    sites, sites_sdf, torch.tensor(d3dsimplices).to(device).detach()
                )

            # do cvt loss on the clipped voronoi vertices positions TODO
            # cvt_loss = lf.compute_cvt_loss_vectorized_delaunay(sites, None, d3dsimplices)

            # cvt_loss = lf.compute_cvt_loss_true(sites, d3dsimplices, faces_or_clippedvert)

            eik_loss = lambda_cvt / 10 * lf.discrete_tet_volume_eikonal_loss(sites, sites_sdf_grads, d3dsimplices)
            # shl = lambda_cvt / 0.1 * lf.smoothed_heaviside_loss(sites, sites_sdf, sites_sdf_grads, d3dsimplices)

            # eik_loss = lambda_cvt / 1000 * lf.tet_sdf_grad_eikonal_loss(sites, tets_sdf_grads, d3dsimplices)

            shl = lambda_cvt / 1 * lf.tet_sdf_motion_mean_curvature_loss(sites, sites_sdf, W, d3dsimplices, eps_H)
            # print("smoothed_heaviside_loss: ", shl.item())

            # sites_eik_loss = lambda_cvt * 0.5 * torch.mean(((sites_sdf_grads**2).sum(dim=1) - 1) ** 2)

            sdf_loss = eik_loss + shl  # sites_eik_loss  # +

            if not mtet:
                cvt_loss = lf.compute_cvt_loss_CLIPPED_vertices(sites, None, None, d3dsimplices, faces_or_clippedvert)
            else:
                cvt_loss = torch.tensor(0)
                eik_loss = torch.tensor(0)
                shl = torch.tensor(0)

            print(
                "eikonal_loss: ",
                eik_loss.item(),
                "cvt_loss: ",
                lambda_cvt / 1 * cvt_loss.item(),
                "chamfer_loss_mesh: ",
                lambda_chamfer * chamfer_loss_mesh.item(),
            )
            sites_loss = lambda_cvt / 1 * cvt_loss + lambda_chamfer * chamfer_loss_mesh

        else:
            sdf_loss = 0
            sites_np = sites.detach().cpu().numpy()
            # d3dsimplices = diffvoronoi.get_delaunay_simplices(sites_np.reshape(input_dims * sites_np.shape[0]))
            d3dsimplices, _ = pygdel3d.triangulate(sites_np)
            d3dsimplices = np.array(d3dsimplices)
            cvt_loss = lf.compute_cvt_loss_vectorized_delaunay(sites, None, d3dsimplices)

            sites_loss = (
                lambda_chamfer * voroloss(mnfld_points.squeeze(0), sites).mean()
            ) + lambda_cvt / 10000 * cvt_loss

        loss = sites_loss  # + sdf_loss
        loss_values.append(loss.item())
        print(f"Epoch {epoch}: loss = {loss.item()}")

        # print(f"before loss.backward(): Allocated: {torch.cuda.memory_allocated() / 1e6} MB, Reserved: {torch.cuda.memory_reserved() / 1e6} MB")
        loss.backward()
        # print(f"After loss.backward(): Allocated: {torch.cuda.memory_allocated() / 1e6} MB, Reserved: {torch.cuda.memory_reserved() / 1e6} MB")
        print("-----------------")

        # torch.nn.utils.clip_grad_norm_(sites_sdf, 1.0)
        # torch.nn.utils.clip_grad_norm_(sites, 1.0)
        optimizer.step()

        # sites_sdf += (sites_sdf_grads*(sites-sites_positions)).sum(dim=1)

        # scheduler.step()
        print("Learning rate: ", optimizer.param_groups[0]["lr"])
        # if epoch>100 and (epoch // 100) == upsampled+1 and loss.item() < 0.5 and upsampled < upsampling:

        # TODO: test epoch == 300 growthrate 300%
        if upsampled < upsampling and epoch / (max_iter * 0.80) > upsampled / upsampling:
            print("sites length BEFORE UPSAMPLING: ", len(sites))
            if len(sites) * 1.09 > grid**3:
                print("Skipping upsampling, too many sites, sites length: ", len(sites), "grid size: ", grid**3)
                upsampled = upsampling
                sites = sites.detach().requires_grad_(True)
                sites_sdf = sites_sdf.detach().requires_grad_(True)

                optimizer = torch.optim.Adam(
                    [
                        {"params": [sites], "lr": lr_sites * 0.1},
                        {"params": [sites_sdf], "lr": lr_sites * 0.1},
                    ]
                )
                eps_H = lf.estimate_eps_H(sites, d3dsimplices, multiplier=1.5 * 3).detach()
                print("Estimated eps_H: ", eps_H)
                # scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.99)
                continue
            # sites, sites_sdf = su.upsampling_vectorized_sites_sites_sdf(sites, tri=None, vor=None, simplices=d3dsimplices, model=sites_sdf)
            # sites, sites_sdf = su.upsampling_curvature_vectorized_sites_sites_sdf(sites, tri=None, vor=None, simplices=d3dsimplices, model=sites_sdf)
            if sites_sdf_grads is None or sites_sdf_grads.shape[0] != sites.shape[0]:
                sites_sdf_grads, tets_sdf_grads, W = su.sdf_space_grad_pytorch_diego_sites_tets(
                    sites, sites_sdf, torch.tensor(d3dsimplices).to(device).detach()
                )

            sites, sites_sdf = su.upsampling_adaptive_vectorized_sites_sites_sdf(
                sites,
                simplices=d3dsimplices,
                model=sites_sdf,
                sites_sdf_grads=sites_sdf_grads,
                ups_method=ups_m,
                score="conservative",
            )
            if voroloss_optim:
                sites_sdf = Hotspot_model(sites)
                sites_sdf = sites_sdf.detach().squeeze(-1).requires_grad_()

            # sites, sites_sdf = su.upsampling_chamfer_vectorized_sites_sites_sdf(
            #     sites, d3dsimplices, sites_sdf, mnfld_points
            # )

            sites = sites.detach().requires_grad_(True)
            sites_sdf = sites_sdf.detach().requires_grad_(True)

            optimizer = torch.optim.Adam(
                [
                    {"params": [sites], "lr": lr_sites * 0.1},
                    {"params": [sites_sdf], "lr": lr_sites * 0.1},
                ]
            )
            # scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.98)
            eps_H = lf.estimate_eps_H(sites, d3dsimplices, multiplier=1.5 * 5).detach()
            print("Estimated eps_H: ", eps_H)

            upsampled += 1.0
            print("sites shape AFTER: ", sites.shape)
            print("sites sdf shape AFTER: ", sites_sdf.shape)

        if epoch % (max_iter / 10) == 0 or epoch == max_iter:
            # print(f"Epoch {epoch}: loss = {loss.item()}")
            # print(f"Best Epoch {best_epoch}: Best loss = {best_loss}")
            # save model and sites
            # ps.register_surface_mesh(f"{epoch} triangle clipped mesh", v_vect.detach().cpu().numpy(), triangle_faces.detach().cpu().numpy())

            # ps.register_point_cloud('sampled points end', hs_p.detach().cpu().numpy())
            # ps.register_point_cloud("sampled points end", v_vect.detach().cpu().numpy(), enabled=False)

            # if f_vect is not None:
            #     ps_mesh = ps.register_surface_mesh(
            #         f"{epoch} sdf clipped pmesh",
            #         v_vect.detach().cpu().numpy(),
            #         f_vect,
            #         back_face_policy="identical",
            #         enabled=False,
            #     )
            #     ps_mesh.add_vector_quantity(
            #         f"{epoch} sdf verts grads",
            #         sdf_verts_grads.detach().cpu().numpy(),
            #         enabled=False,
            #     )

            site_file_path = (
                f"{destination}{mesh[0]}{max_iter}_{epoch}_3d_sites_{num_centroids}_chamfer{lambda_chamfer}.pth"
            )
            # model_file_path = f'{destination}{mesh[0]}{max_iter}_{epoch}_3d_model_{num_centroids}_chamfer{lambda_chamfer}.pth'
            sdf_file_path = (
                f"{destination}{mesh[0]}{max_iter}_{epoch}_3d_sdf_{num_centroids}_chamfer{lambda_chamfer}.pth"
            )
            torch.save(sites_sdf, sdf_file_path)
            torch.save(sites, site_file_path)

        epoch += 1

    return sites, sites_sdf

In [8]:
# lambda_weights = [252,0,0,0,10.211111,0,100,0]
# lambda_weights = [500,0,0,0,1000,0,100,0]
lambda_weights = [100, 0, 0, 0, 1000, 0, 100, 0]


lambda_cvt = lambda_weights[0]
lambda_sdf = lambda_weights[1]
lambda_min_distance = lambda_weights[2]
lambda_laplace = lambda_weights[3]
lambda_chamfer = lambda_weights[4]
lambda_eikonal = lambda_weights[5]
lambda_domain_restriction = lambda_weights[6]
lambda_true_points = lambda_weights[7]

max_iter = 1000
voroloss_optim = False
ups = 10

In [9]:
site_file_path = f"{destination}{max_iter}_cvt_{lambda_cvt}_chamfer_{lambda_chamfer}_eikonal_{lambda_eikonal}.npy"

# check if optimized sites file exists
if not os.path.exists(site_file_path):
    # import sites
    print("Importing sites")
    sites = np.load(site_file_path)
    sites = torch.from_numpy(sites).to(device).requires_grad_(True)
else:
    # import cProfile, pstats
    # import time

    # profiler = cProfile.Profile()
    # profiler.enable()

    # with torch.profiler.profile(
    #     activities=[
    #         torch.profiler.ProfilerActivity.CPU,
    #         torch.profiler.ProfilerActivity.CUDA,
    #     ],
    #     record_shapes=False,
    #     with_stack=True,  # Captures function calls
    # ) as prof:
    #     sites, optimized_sites_sdf = train_DCCVT(
    #         sites, sdf0, max_iter=max_iter, upsampling=0, lambda_weights=lambda_weights
    #     )

    # print(prof.key_averages().table(sort_by="self_cuda_time_total"))
    # prof.export_chrome_trace("trace.json")

    sites, optimized_sites_sdf = train_DCCVT(
        sites,
        sdf0,
        max_iter=max_iter,
        upsampling=ups,
        lambda_weights=lambda_weights,
        voroloss_optim=voroloss_optim,
        Hotspot_model=model if voroloss_optim else None,
    )

    sites_np = sites.detach().cpu().numpy()
    np.save(site_file_path, sites_np)

print("Sites length: ", len(sites))
print("min sites: ", torch.min(sites))
print("max sites: ", torch.max(sites))

Estimated eps_H:  tensor(1.1722, device='cuda:0')
eikonal_loss:  17.05349349975586 cvt_loss:  4.388182610273361 chamfer_loss_mesh:  1.7202278831973672
Epoch 0: loss = 6.108410358428955
-----------------
Learning rate:  0.0005
eikonal_loss:  17.6711483001709 cvt_loss:  4.24342155456543 chamfer_loss_mesh:  1.6681974520906806
Epoch 1: loss = 5.911619186401367
-----------------
Learning rate:  0.0005
sites length BEFORE UPSAMPLING:  4096
Sampled indices: 158 out of 304 candidates (M=304)
Estimated eps_H:  tensor(1.1702, device='cuda:0')
sites shape AFTER:  torch.Size([4728, 3])
sites sdf shape AFTER:  torch.Size([4728])
eikonal_loss:  19.17742156982422 cvt_loss:  3.749532252550125 chamfer_loss_mesh:  1.1780207278206944
Epoch 2: loss = 4.927553176879883
-----------------
Learning rate:  0.0005


KeyboardInterrupt: 

In [10]:
epoch = 1000

# model_file_path = f'{destination}{mesh[0]}{max_iter}_{epoch}_3d_model_{num_centroids}_chamfer{lambda_chamfer}.pth'
site_file_path = f"{destination}{mesh[0]}{max_iter}_{epoch}_3d_sites_{num_centroids}_chamfer{lambda_chamfer}.pth"
sdf_file_path = f"{destination}{mesh[0]}{max_iter}_{epoch}_3d_sdf_{num_centroids}_chamfer{lambda_chamfer}.pth"


sites = torch.load(site_file_path)
sdf_v = torch.load(sdf_file_path)
if voroloss_optim:
    sdf_v = model(sites).squeeze(-1)


sites_np = sites.detach().cpu().numpy()
print("sdf", sdf_v.shape)
print("sites", site_file_path)

ps_cloud_f = ps.register_point_cloud(f"{epoch} epoch_cvt_grid", sites_np)
ps_cloud_f.add_scalar_quantity(
    "vis_grid_pred",
    sdf_v.detach().cpu().numpy(),
    enabled=True,
    cmap="coolwarm",
    vminmax=(-0.15, 0.15),
)

print("sites_np shape: ", sites_np.shape)

# print sites if Nan
if np.isnan(sites_np).any():
    print("sites_np contains NaN values")
    print("sites_np NaN values: ", np.isnan(sites_np).sum())
# remove nan values from sites tensor
sites_np = sites_np[~np.isnan(sites_np).any(axis=1)]
sites = torch.from_numpy(sites_np).to(device).requires_grad_(True)

sdf torch.Size([36056])
sites ./images/autograd/End2End_DCCVT_interpolSDF/hole_gargoyle1000_1000_3d_sites_4096_chamfer1000.pth
sites_np shape:  (36056, 3)


In [11]:
# metric between sites sdf values and their corresponding sdf values on hotspot model
# true_Sdf = model(sites).squeeze(-1)
d3dsimplices, _ = pygdel3d.triangulate(sites_np)
d3dsimplices = torch.tensor(d3dsimplices, device=device)

In [ ]:
# v_vect, f_vect = su.get_clipped_mesh_numba(sites, model, None, True)
# ps.register_surface_mesh("model final clipped polygon mesh", v_vect.detach().cpu().numpy(), f_vect)

# v_vect, f_vect = su.get_clipped_mesh_numba(sites, model, None, False)
# ps.register_surface_mesh("model final polygon mesh", v_vect.detach().cpu().numpy(), f_vect)

######################################################

# if mesh[0] == "sphere":
#     # generate sphere sdf
#     print("Generating sphere SDF")
#     sdf_v = sphere_sdf(sites, torch.zeros(3).to(device), 0.50)

(
    v_vect,
    f_vect,
    _,
    _,
    _,
) = su.get_clipped_mesh_numba(sites, None, None, False, sdf_v, True)

output_obj_file = f"{destination}{mesh[0]}_unclipped.obj"
su.save_obj(output_obj_file, v_vect.detach().cpu().numpy(), f_vect)


# f_vect = [[f[0], f[i], f[i + 1]] for f in f_vect for i in range(1, len(f) - 1)]

ps.register_surface_mesh(
    "sdf final unclipped polygon mesh",
    v_vect.detach().cpu().numpy(),
    f_vect,
    back_face_policy="identical",
    enabled=False,
)

if voroloss_optim:
    ps.show()

p, faces = su.cvt_extraction(sites, sdf_v, d3dsimplices.detach().cpu().numpy(), True)
output_obj_file = f"{destination}{mesh[0]}_interpol_extract.obj"
su.save_obj(output_obj_file, p.detach().cpu().numpy(), faces)
# ps.register_point_cloud("cvt extraction", p.detach().cpu().numpy())
ps.register_surface_mesh("cvt extraction final", p.detach().cpu().numpy(), faces, back_face_policy="identical")


v_vect, f_vect, _, _, _ = su.get_clipped_mesh_numba(sites, None, None, True, sdf_v, True)
output_obj_file = f"{destination}{mesh[0]}_proj_extract.obj"
su.save_obj(output_obj_file, v_vect.detach().cpu().numpy(), f_vect)
# f_vect = [[f[0], f[i], f[i + 1]] for f in f_vect for i in range(1, len(f) - 1)]
ps.register_surface_mesh(
    "sdf final clipped polygon mesh", v_vect.detach().cpu().numpy(), f_vect, back_face_policy="identical"
)
# f_vect = [[f[0], f[i], f[i + 1]] for f in f_vect for i in range(1, len(f) - 1)]

d3dsimplices, _ = pygdel3d.triangulate(sites_np)
d3dsimplices = torch.tensor(d3dsimplices, device=device)
marching_tetrehedra_mesh = kaolin.ops.conversions.marching_tetrahedra(
    sites.unsqueeze(0), d3dsimplices, sdf_v.unsqueeze(0), return_tet_idx=False
)
vertices_list, faces_list = marching_tetrehedra_mesh
v_vect = vertices_list[0]
faces = faces_list[0]

ps.register_surface_mesh(
    "MTET", v_vect.detach().cpu().numpy(), faces.detach().cpu().numpy(), back_face_policy="identical"
)

# export obj file
output_obj_file = f"{destination}{mesh[0]}_MT.obj"
output_ply_file = (
    f"{destination}{mesh[0]}{max_iter}_{epoch}_3d_sites_{num_centroids}_chamfer{lambda_chamfer}_targetpointcloud.ply"
)
su.save_obj(output_obj_file, v_vect.detach().cpu().numpy(), faces)
# su.save_target_pc_ply(output_ply_file, mnfld_points.squeeze(0).detach().cpu().numpy())


ps.show()

Computing Delaunay simplices...
Number of Delaunay simplices: 213601
Delaunay simplices shape: [[   17   259     3   257]
 [  512     0   514   257]
 [18337 30380 20403 32341]
 ...
 [34384 34385 35740 22725]
 [34385 34384 34387 29320]
 [34385 35740 34387 34384]]
Max vertex index in simplices: 36055
Min vertex index in simplices: 0
Site index range: 36056
Computing Delaunay simplices...
Number of Delaunay simplices: 213601
Delaunay simplices shape: [[   17   259     3   257]
 [26874  5921 27290 35834]
 [    2    16     0    17]
 ...
 [26662 33206 33379 26660]
 [16555 33039 25235 16553]
 [33037 25235 33039 16553]]
Max vertex index in simplices: 36055
Min vertex index in simplices: 0
Site index range: 36056


: 

In [ ]:
import voronoiaccel

ERROR_SCALE = 1e5  # Scale the error metrics to match the unit of the model (e.g., if model is in cm, scale by 100)
obj_pts, obj_normals, obj_mesh = su.sample_points_on_mesh(obj_path, n_points=N_POINTS, GT=False)
gt_mesh, gt_normals, gt_mesh = su.sample_points_on_mesh(obj_path, GT=True)
cd1, cd2, f1, nc, recall, precision, completeness1, completeness2, accuracy1, accuracy2 = (
    voronoiaccel.compute_error_fcpw(
        np.array(gt_mesh.vertices),
        np.array(gt_mesh.faces).astype(np.int32),
        np.array(gt_pts),
        np.array(gt_normals),
        np.array(obj_mesh.vertices),
        np.array(obj_mesh.faces).astype(np.int32),
        np.array(obj_pts),
        np.array(obj_normals),
        0.003,
        0.45,
    )
)
cd2 = cd2 * ERROR_SCALE  # Scale the Chamfer distance
cd1 = cd1 * ERROR_SCALE  # Scale the Chamfer distance
completeness1 = completeness1 * ERROR_SCALE  # Scale the completeness
completeness2 = completeness2 * ERROR_SCALE  # Scale the completeness
accuracy1 = accuracy1 * ERROR_SCALE  # Scale the accuracy
accuracy2 = accuracy2 * ERROR_SCALE  # Scale the accuracy

errors[obj_path] = {
    "cd1": cd1,
    "cd2": cd2,
    "f1": f1,
    "nc": nc,
    "recall": recall,
    "precision": precision,
    "completeness1": completeness1,
    "completeness2": completeness2,
    "accuracy1": accuracy1,
    "accuracy2": accuracy2,
}
print(
    f"  CD: {cd2:.4f},\t F1: {f1:.4f},\t NC: {nc:.4f},\t Recall: {recall:.4f},\t Precision: {precision:.4f},\t Completeness2: {completeness2:.4f},\t Accuracy2: {accuracy2:.4f}"
)

In [ ]:
# sites, sdf = train_DCCVT(
#     sites, sdf_v, max_iter=max_iter, upsampling=0, lambda_weights=lambda_weights, voroloss_optim=True
# )
# (
#     v_vect,
#     f_vect,
#     _,
#     _,
#     _,
# ) = su.get_clipped_mesh_numba(sites, None, None, False, sdf, True)
# ps.register_surface_mesh("voromeh sdf final unclipped polygon mesh", v_vect.detach().cpu().numpy(), f_vect)


# v_vect, f_vect, _, _, _ = su.get_clipped_mesh_numba(sites, None, None, True, sdf, True)
# ps.register_surface_mesh("voromeh sdf final clipped polygon mesh", v_vect.detach().cpu().numpy(), f_vect)
# # f_vect = [[f[0], f[i], f[i + 1]] for f in f_vect for i in range(1, len(f) - 1)]
# ps.show()


In [ ]:
# chamfer metric
# add sampled points to polyscope and ground truth mesh to polyscope

import trimesh


def sample_points_on_mesh(mesh_path, n_points=100000):
    mesh = trimesh.load(mesh_path)
    # normalize mesh
    mesh.apply_translation(-mesh.centroid)
    mesh.apply_scale(1.0 / np.max(np.abs(mesh.vertices)))
    # export mesh to obj file
    mesh.export(mesh_path.replace(".obj", ".obj"))
    print(mesh_path)
    points, _ = trimesh.sample.sample_surface(mesh, n_points)
    return points, mesh


import numpy as np
from scipy.spatial import cKDTree


def chamfer_accuracy_completeness(ours_pts, gt_pts):
    # Completeness: GT → Ours
    dists_gt_to_ours = cKDTree(ours_pts).query(gt_pts, k=1)[0]
    completeness = np.mean(dists_gt_to_ours**2)

    # Accuracy: Ours → GT
    dists_ours_to_gt = cKDTree(gt_pts).query(ours_pts, k=1)[0]
    accuracy = np.mean(dists_ours_to_gt**2)

    return accuracy, completeness


ours_pts, _ = sample_points_on_mesh(output_obj_file, n_points=100000)
m = mesh[1].replace("data", "mesh")
gt_pts, _ = sample_points_on_mesh(m + ".obj", n_points=100000)

acc, comp = chamfer_accuracy_completeness(ours_pts, gt_pts)

print(f"Chamfer Accuracy (Ours → GT): {acc:.6f}")
print(f"Chamfer Completeness (GT → Ours): {comp:.6f}")
print(f"Chamfer Distance (symmetric): {acc + comp:.6f}")


/home/wylliam/dev/Kyushu_experiments-1/venv/lib/python3.12/site-packages/trimesh/base.py:605: RuntimeWarning: Mean of empty slice.
  centroid = self.triangles_center.mean(axis=0)
/home/wylliam/dev/Kyushu_experiments-1/venv/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


ValueError: Translation must be (3,) or (2,)!

In [ ]:
# import os
# import trimesh
# import numpy as np


# def sample_points_on_mesh(mesh_path, n_points=32 * 32 * 150, GT=True):
#     mesh = trimesh.load(mesh_path)
#     points, idx = trimesh.sample.sample_surface(mesh, n_points)
#     normals = mesh.face_normals[idx]  # Get normals at sampled points

#     if GT:
#         # Center the point cloud
#         points = np.asarray(points, dtype=np.float32)
#         center = points.mean(axis=0)
#         points -= center

#         # Compute scale factor (same as HotSpot)
#         scale = np.percentile(np.linalg.norm(points, axis=-1), 70) / 0.45
#         scale = max(scale, np.abs(points).max())
#         points /= scale

#         # Apply same normalization to mesh vertices
#         mesh.vertices = (mesh.vertices - center) / scale

#         mesh.export(mesh_path.replace(".obj", ".obj"))
#         # Save sampled points as a .ply file using trimesh
#         pc = trimesh.PointCloud(points)
#         pc.export(mesh_path.replace(".obj", ".ply"))

#     return points, normals, mesh


# thingi32_150k_dir = "/home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/"
# all_mesh = [m for m in os.listdir(thingi32_150k_dir) if m.endswith(".obj")]
# for mesh in all_mesh:
#     print("Processing mesh: ", mesh)
#     m = thingi32_150k_dir + mesh
#     points, normals, mesh = sample_points_on_mesh(m)
#     print("Sampled points shape: ", points.shape)
#     print("Sampled normals shape: ", normals.shape)
#     print("Normalized mesh saved to: ", m.replace(".obj", "_norm.obj"))
#     print("Sampled points saved to: ", m.replace(".obj", ".ply"))

Processing mesh:  68381.obj
Sampled points shape:  (153600, 3)
Sampled normals shape:  (153600, 3)
Normalized mesh saved to:  /home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/68381_norm.obj
Sampled points saved to:  /home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/68381.ply
Processing mesh:  79241.obj
Sampled points shape:  (153600, 3)
Sampled normals shape:  (153600, 3)
Normalized mesh saved to:  /home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/79241_norm.obj
Sampled points saved to:  /home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/79241.ply
Processing mesh:  68380.obj
Sampled points shape:  (153600, 3)
Sampled normals shape:  (153600, 3)
Normalized mesh saved to:  /home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/68380_norm.obj
Sampled points saved to:  /home/wylliam/dev/Kyushu_experiments/mesh/thingi32_150k/68380.ply
Processing mesh:  72870.obj
Sampled points shape:  (153600, 3)
Sampled normals shape:  (153600, 3)
Normalized mesh saved to:  /home/w