In [ ]:
import kaolin
import numpy as np
import os

file_path = '../data/eabxhqb82fxu'
samples = 90000
mesh = kaolin.io.mesh.import_mesh(file_path+'.obj',triangulate=True)
mesh.to_batched()
pointcloud = kaolin.ops.mesh.sample_points(mesh.vertices, mesh.faces, samples)

#reshape pointcloud for export
pc = np.reshape(pointcloud[0], (samples, 3))
#insert noise to point using gaussian noise with zero mean of stadard deviation 0.005
pc = pc + np.random.normal(-0.025, 0.025, pc.shape)

    
#kaolin.io.usd.export_pointcloud(file_path+'.usd', pc)

print(pointcloud)

In [1]:
# import trimesh
# import pysdf
# from pysdf import SDF
# o = trimesh.load('../data/eabxhqb82fxu.obj')
# f = SDF(o.vertices, o.faces)
# print(f)
from mesh_to_sdf import sample_sdf_near_surface

import trimesh

import numpy as np

mesh = trimesh.load('../data/32770.obj')

points, sdf = sample_sdf_near_surface(mesh, number_of_points=250000)

print(points)
print(sdf)

[[ 0.26191002  0.13839577 -0.16950892]
 [ 0.2444509   0.26517048 -0.16831435]
 [-0.6241365   0.0796451  -0.34082392]
 ...
 [ 0.43410867  0.07256026  0.75327003]
 [ 0.87913495 -0.18856849 -0.16335867]
 [-0.32484394 -0.5460615   0.04001618]]
[ 0.00143934 -0.00210138  0.00142516 ...  0.54324716  0.19471256
  0.24180326]
