In [19]:
import kaolin
import numpy as np
import os

file_path = '../data/eabxhqb82fxu'
samples = 90000
mesh = kaolin.io.mesh.import_mesh(file_path+'.obj',triangulate=True)
mesh.to_batched()
pointcloud = kaolin.ops.mesh.sample_points(mesh.vertices, mesh.faces, samples)

#reshape pointcloud for export
pc = np.reshape(pointcloud[0], (samples, 3))
#insert noise to point using gaussian noise with zero mean of stadard deviation 0.005
pc = pc + np.random.normal(-0.025, 0.025, pc.shape)

    
#kaolin.io.usd.export_pointcloud(file_path+'.usd', pc)

print(pointcloud)

(tensor([[[-2.2874e+01,  1.0270e+01, -2.7000e-03],
         [ 1.5325e+01,  2.0104e+01,  2.5498e+01],
         [ 3.3422e+00,  7.2627e+00,  6.1880e+01],
         ...,
         [ 2.8590e+00,  8.7899e+00,  6.2214e+01],
         [-4.4499e+00,  2.1178e+01,  5.3627e+01],
         [-8.8248e+00,  1.0199e+01,  3.0900e+01]]]), tensor([[ 1017,  7611, 15689,  ..., 15866, 11035,  3237]]))


In [ ]:
import polyscope as ps
import open3d as o3d
import numpy as np

file_path = '../data/bunny'
samples = 128**3
mesh = o3d.io.read_triangle_mesh(file_path+".obj")
#sample points on the mesh
pointcloud = mesh.sample_points_uniformly(number_of_points=samples)
#save pointcloud to file
o3d.io.write_point_cloud(file_path+'.ply', pointcloud)
#load pointcloud from file
pointcloud = o3d.io.read_point_cloud(file_path+'.ply')
#visualize pointcloud
# vis = o3d.visualization.Visualizer()
# vis.create_window()
# vis.add_geometry(pointcloud)
# vis.run()
# vis.destroy_window()
#visualize pointcloud using polyscope
ps.init()
pointcloud = np.asarray(pointcloud.points)
ps.register_point_cloud("pointcloud init", pointcloud)
ps.register_surface_mesh("mesh init", np.asarray(mesh.vertices), np.asarray(mesh.triangles))
# ps.show()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 3.3.0 NVIDIA 570.144


In [21]:
#output from HotSpot :
#load mesh
mesh = o3d.io.read_triangle_mesh("/home/wylliam/dev/Kyushu_experiments/output.ply")
pointcloud = mesh.sample_points_uniformly(number_of_points=samples)

ps.init()
pointcloud = np.asarray(pointcloud.points)
ps.register_point_cloud("pointcloud output", pointcloud)
ps.register_surface_mesh("mesh output", np.asarray(mesh.vertices), np.asarray(mesh.triangles))


ps.show()

In [ ]:
# import trimesh
# import pysdf
# from pysdf import SDF
# o = trimesh.load('../data/eabxhqb82fxu.obj')
# f = SDF(o.vertices, o.faces)
# print(f)
from mesh_to_sdf import sample_sdf_near_surface

import trimesh

import numpy as np

mesh = trimesh.load('../data/32770.obj')

points, sdf = sample_sdf_near_surface(mesh, number_of_points=250000)

print(points)
print(sdf)

[[ 0.26191002  0.13839577 -0.16950892]
 [ 0.2444509   0.26517048 -0.16831435]
 [-0.6241365   0.0796451  -0.34082392]
 ...
 [ 0.43410867  0.07256026  0.75327003]
 [ 0.87913495 -0.18856849 -0.16335867]
 [-0.32484394 -0.5460615   0.04001618]]
[ 0.00143934 -0.00210138  0.00142516 ...  0.54324716  0.19471256
  0.24180326]
